##[group]Run <:*:>
with:
python-version: <:*:>
cache: pip
cache-dependency-path: tests/requirements/py3.txt
check-latest: false
token: ***
<:*:> true
<:*:> false
<:*:> false
##[endgroup]
##[group]Installed versions
Successfully set up CPython (<:NUM:>.<:NUM:>.<:NUM:>)
##[endgroup]
[command]/opt/hostedtoolcache/Python/3.13.2/x64/bin/pip cache dir
/home/runner/.cache/pip
Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.13.2-pip-5bace0b3ae2fdf078d3a74eba03881213770dd8d7f85c4040b3ae9ec9d592d8e
Received 45102031 of 45102031 (100.0%), 105.2 MBs/sec
Cache Size: ~43 MB (45102031 B)
[command]/usr/bin/tar -xf /home/runner/work/_temp/a1255503-366c-4869-9aa2-5c468d722413/cache.tzst -P -C /home/runner/work/django/django --use-compress-program unzstd
Cache restored successfully
Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.13.2-pip-5bace0b3ae2fdf078d3a74eba03881213770dd8d7f85c4040b3ae9ec9d592d8e
