2025-04-13T15:50:19.4856854Z ##[group]Run cd packages/markitdown; hatch test
2025-04-13T15:50:19.4857323Z [36;1mcd packages/markitdown; hatch test[0m
2025-04-13T15:50:19.4907705Z shell: /usr/bin/bash -e {0}
2025-04-13T15:50:19.4908171Z env:
2025-04-13T15:50:19.4908478Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T15:50:19.4908951Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
2025-04-13T15:50:19.4909389Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T15:50:19.4909801Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T15:50:19.4910224Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T15:50:19.4910946Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib:/opt/hostedtoolcache/Python/3.11.11/x64/lib:/opt/hostedtoolcache/Python/3.10.16/x64/lib
2025-04-13T15:50:19.4911592Z ##[endgroup]
2025-04-13T15:50:19.7158289Z Creating environment: hatch-test.py3.12
2025-04-13T15:50:19.7638807Z Installing project in development mode
2025-04-13T15:50:21.6629032Z Checking dependencies
2025-04-13T15:50:21.7079221Z Syncing dependencies
2025-04-13T15:50:26.3902403Z ============================= test session starts ==============================
2025-04-13T15:50:26.3903422Z platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
2025-04-13T15:50:26.3904267Z rootdir: /home/runner/work/markitdown/markitdown/packages/markitdown
2025-04-13T15:50:26.3905017Z configfile: pyproject.toml
2025-04-13T15:50:26.3905619Z plugins: rerunfailures-14.0, anyio-4.9.0, xdist-3.6.1, mock-3.14.0
2025-04-13T15:50:26.3906252Z collected 172 items
2025-04-13T15:50:26.3906489Z 
2025-04-13T15:50:28.1042027Z tests/test_cli_misc.py ..                                                [  1%]
2025-04-13T15:51:03.7243029Z tests/test_cli_vectors.py ......F...........F...........F.....ssssssssss [ 27%]
2025-04-13T15:51:05.6552894Z ss..                                                                     [ 30%]
2025-04-13T15:51:05.9769727Z tests/test_module_misc.py ......ss.ss                                    [ 36%]
2025-04-13T15:51:09.5460217Z tests/test_module_vectors.py ........................F..............F... [ 61%]
2025-04-13T15:51:16.0876182Z ...........F.....sssssssssssssss.........F..............F.........       [100%]
2025-04-13T15:51:16.0877706Z 
2025-04-13T15:51:16.0878143Z =================================== FAILURES ===================================
2025-04-13T15:51:16.0878885Z _____________________ test_output_to_stdout[test_vector6] ______________________
2025-04-13T15:51:16.0879314Z 
2025-04-13T15:51:16.0879647Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T15:51:16.0881451Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0882526Z 
2025-04-13T15:51:16.0882834Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T15:51:16.0883637Z     def test_output_to_stdout(shared_tmp_dir, test_vector) -> None:
2025-04-13T15:51:16.0884353Z         """Test that the CLI outputs to stdout correctly."""
2025-04-13T15:51:16.0884847Z     
2025-04-13T15:51:16.0885197Z         result = subprocess.run(
2025-04-13T15:51:16.0885641Z             [
2025-04-13T15:51:16.0885988Z                 "python",
2025-04-13T15:51:16.0886378Z                 "-m",
2025-04-13T15:51:16.0886758Z                 "markitdown",
2025-04-13T15:51:16.0887269Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T15:51:16.0887797Z             ],
2025-04-13T15:51:16.0888370Z             capture_output=True,
2025-04-13T15:51:16.0888818Z             text=True,
2025-04-13T15:51:16.0889184Z         )
2025-04-13T15:51:16.0889483Z     
2025-04-13T15:51:16.0890050Z         assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
2025-04-13T15:51:16.0891742Z         for test_string in test_vector.must_include:
2025-04-13T15:51:16.0892330Z >           assert test_string in result.stdout
2025-04-13T15:51:16.0893956Z E           assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n'
2025-04-13T15:51:16.0896838Z E            +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
2025-04-13T15:51:16.0898954Z 
2025-04-13T15:51:16.0899223Z tests/test_cli_vectors.py:67: AssertionError
2025-04-13T15:51:16.0899879Z ______________________ test_output_to_file[test_vector6] _______________________
2025-04-13T15:51:16.0900377Z 
2025-04-13T15:51:16.0900722Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T15:51:16.0902448Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0903474Z 
2025-04-13T15:51:16.0903714Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T15:51:16.0904180Z     def test_output_to_file(shared_tmp_dir, test_vector) -> None:
2025-04-13T15:51:16.0904579Z         """Test that the CLI outputs to a file correctly."""
2025-04-13T15:51:16.0904870Z     
2025-04-13T15:51:16.0905174Z         output_file = os.path.join(shared_tmp_dir, test_vector.filename + ".output")
2025-04-13T15:51:16.0905569Z         result = subprocess.run(
2025-04-13T15:51:16.0905807Z             [
2025-04-13T15:51:16.0906006Z                 "python",
2025-04-13T15:51:16.0906459Z                 "-m",
2025-04-13T15:51:16.0906668Z                 "markitdown",
2025-04-13T15:51:16.0906895Z                 "-o",
2025-04-13T15:51:16.0907105Z                 output_file,
2025-04-13T15:51:16.0907406Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T15:51:16.0907709Z             ],
2025-04-13T15:51:16.0907911Z             capture_output=True,
2025-04-13T15:51:16.0908392Z             text=True,
2025-04-13T15:51:16.0908592Z         )
2025-04-13T15:51:16.0908762Z     
2025-04-13T15:51:16.0909071Z         assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
2025-04-13T15:51:16.0909560Z         assert os.path.exists(output_file), f"Output file not created: {output_file}"
2025-04-13T15:51:16.0909921Z     
2025-04-13T15:51:16.0910124Z         with open(output_file, "r") as f:
2025-04-13T15:51:16.0910400Z             output_data = f.read()
2025-04-13T15:51:16.0910696Z             for test_string in test_vector.must_include:
2025-04-13T15:51:16.0911020Z >               assert test_string in output_data
2025-04-13T15:51:16.0911687Z E               AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0912089Z 
2025-04-13T15:51:16.0912219Z tests/test_cli_vectors.py:96: AssertionError
2025-04-13T15:51:16.0912605Z ______________ test_input_from_stdin_without_hints[test_vector6] _______________
2025-04-13T15:51:16.0912876Z 
2025-04-13T15:51:16.0913078Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T15:51:16.0914029Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0914584Z 
2025-04-13T15:51:16.0914758Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T15:51:16.0915207Z     def test_input_from_stdin_without_hints(shared_tmp_dir, test_vector) -> None:
2025-04-13T15:51:16.0915634Z         """Test that the CLI readds from stdin correctly."""
2025-04-13T15:51:16.0915920Z     
2025-04-13T15:51:16.0916107Z         test_input = b""
2025-04-13T15:51:16.0916628Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T15:51:16.0917029Z             test_input = stream.read()
2025-04-13T15:51:16.0917331Z     
2025-04-13T15:51:16.0917517Z         result = subprocess.run(
2025-04-13T15:51:16.0917749Z             [
2025-04-13T15:51:16.0918156Z                 "python",
2025-04-13T15:51:16.0918406Z                 "-m",
2025-04-13T15:51:16.0918631Z                 "markitdown",
2025-04-13T15:51:16.0918924Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T15:51:16.0919225Z             ],
2025-04-13T15:51:16.0919431Z             input=test_input,
2025-04-13T15:51:16.0919676Z             capture_output=True,
2025-04-13T15:51:16.0919914Z             text=False,
2025-04-13T15:51:16.0920116Z         )
2025-04-13T15:51:16.0920295Z     
2025-04-13T15:51:16.0920578Z         stdout = result.stdout.decode(locale.getpreferredencoding())
2025-04-13T15:51:16.0920922Z         assert (
2025-04-13T15:51:16.0921141Z             result.returncode == 0
2025-04-13T15:51:16.0921456Z         ), f"CLI exited with error: {result.stderr.decode('utf-8')}"
2025-04-13T15:51:16.0921805Z         for test_string in test_vector.must_include:
2025-04-13T15:51:16.0922104Z >           assert test_string in stdout
2025-04-13T15:51:16.0922726Z E           AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n'
2025-04-13T15:51:16.0923088Z 
2025-04-13T15:51:16.0923218Z tests/test_cli_vectors.py:129: AssertionError
2025-04-13T15:51:16.0923583Z _______________________ test_convert_local[test_vector9] _______________________
2025-04-13T15:51:16.0923835Z 
2025-04-13T15:51:16.0924649Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0925201Z 
2025-04-13T15:51:16.0925426Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T15:51:16.0925810Z     def test_convert_local(test_vector):
2025-04-13T15:51:16.0926117Z         """Test the conversion of a local file."""
2025-04-13T15:51:16.0926414Z         markitdown = MarkItDown()
2025-04-13T15:51:16.0926646Z     
2025-04-13T15:51:16.0926856Z         result = markitdown.convert(
2025-04-13T15:51:16.0927237Z             os.path.join(TEST_FILES_DIR, test_vector.filename), url=test_vector.url
2025-04-13T15:51:16.0927588Z         )
2025-04-13T15:51:16.0927817Z         for string in test_vector.must_include:
2025-04-13T15:51:16.0928319Z >           assert string in result.markdown
2025-04-13T15:51:16.0928948Z E           AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0929867Z E            +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f441aae0>.markdown
2025-04-13T15:51:16.0930371Z 
2025-04-13T15:51:16.0930518Z tests/test_module_vectors.py:69: AssertionError
2025-04-13T15:51:16.0930927Z _________________ test_convert_stream_with_hints[test_vector9] _________________
2025-04-13T15:51:16.0931202Z 
2025-04-13T15:51:16.0931881Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0932441Z 
2025-04-13T15:51:16.0932642Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T15:51:16.0933042Z     def test_convert_stream_with_hints(test_vector):
2025-04-13T15:51:16.0933435Z         """Test the conversion of a stream with full stream info."""
2025-04-13T15:51:16.0933776Z         markitdown = MarkItDown()
2025-04-13T15:51:16.0934001Z     
2025-04-13T15:51:16.0934345Z         stream_info = StreamInfo(
2025-04-13T15:51:16.0934675Z             extension=os.path.splitext(test_vector.filename)[1],
2025-04-13T15:51:16.0935024Z             mimetype=test_vector.mimetype,
2025-04-13T15:51:16.0935319Z             charset=test_vector.charset,
2025-04-13T15:51:16.0935566Z         )
2025-04-13T15:51:16.0935737Z     
2025-04-13T15:51:16.0936063Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T15:51:16.0936464Z             result = markitdown.convert(
2025-04-13T15:51:16.0936802Z                 stream, stream_info=stream_info, url=test_vector.url
2025-04-13T15:51:16.0937117Z             )
2025-04-13T15:51:16.0937352Z             for string in test_vector.must_include:
2025-04-13T15:51:16.0937677Z >               assert string in result.markdown
2025-04-13T15:51:16.0938512Z E               AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0939488Z E                +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f63ba8d0>.markdown
2025-04-13T15:51:16.0939967Z 
2025-04-13T15:51:16.0940113Z tests/test_module_vectors.py:90: AssertionError
2025-04-13T15:51:16.0940526Z _______________ test_convert_stream_without_hints[test_vector9] ________________
2025-04-13T15:51:16.0940797Z 
2025-04-13T15:51:16.0941472Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0942193Z 
2025-04-13T15:51:16.0942403Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T15:51:16.0942804Z     def test_convert_stream_without_hints(test_vector):
2025-04-13T15:51:16.0943186Z         """Test the conversion of a stream with no stream info."""
2025-04-13T15:51:16.0943528Z         markitdown = MarkItDown()
2025-04-13T15:51:16.0943761Z     
2025-04-13T15:51:16.0944090Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T15:51:16.0944552Z             result = markitdown.convert(stream, url=test_vector.url)
2025-04-13T15:51:16.0944910Z             for string in test_vector.must_include:
2025-04-13T15:51:16.0945216Z >               assert string in result.markdown
2025-04-13T15:51:16.0945811Z E               AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0946703Z E                +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f7bf4890>.markdown
2025-04-13T15:51:16.0947176Z 
2025-04-13T15:51:16.0947453Z tests/test_module_vectors.py:103: AssertionError
2025-04-13T15:51:16.0947843Z _____________________ test_convert_file_uri[test_vector9] ______________________
2025-04-13T15:51:16.0948327Z 
2025-04-13T15:51:16.0949034Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0949585Z 
2025-04-13T15:51:16.0949785Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T15:51:16.0950153Z     def test_convert_file_uri(test_vector):
2025-04-13T15:51:16.0950462Z         """Test the conversion of a file:// URI."""
2025-04-13T15:51:16.0950761Z         markitdown = MarkItDown()
2025-04-13T15:51:16.0951004Z     
2025-04-13T15:51:16.0951218Z         result = markitdown.convert(
2025-04-13T15:51:16.0951600Z             Path(os.path.join(TEST_FILES_DIR, test_vector.filename)).as_uri(),
2025-04-13T15:51:16.0951959Z             url=test_vector.url,
2025-04-13T15:51:16.0952195Z         )
2025-04-13T15:51:16.0952427Z         for string in test_vector.must_include:
2025-04-13T15:51:16.0952732Z >           assert string in result.markdown
2025-04-13T15:51:16.0953316Z E           AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0954194Z E            +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f9ef8260>.markdown
2025-04-13T15:51:16.0954697Z 
2025-04-13T15:51:16.0954846Z tests/test_module_vectors.py:139: AssertionError
2025-04-13T15:51:16.0955382Z _____________________ test_convert_data_uri[test_vector9] ______________________
2025-04-13T15:51:16.0955641Z 
2025-04-13T15:51:16.0956350Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T15:51:16.0956932Z 
2025-04-13T15:51:16.0957128Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T15:51:16.0957499Z     def test_convert_data_uri(test_vector):
2025-04-13T15:51:16.0957809Z         """Test the conversion of a data URI."""
2025-04-13T15:51:16.0958219Z         markitdown = MarkItDown()
2025-04-13T15:51:16.0958444Z     
2025-04-13T15:51:16.0958622Z         data = ""
2025-04-13T15:51:16.0958973Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T15:51:16.0959425Z             data = base64.b64encode(stream.read()).decode("utf-8")
2025-04-13T15:51:16.0959763Z         mimetype = test_vector.mimetype
2025-04-13T15:51:16.0960075Z         data_uri = f"data:{mimetype};base64,{data}"
2025-04-13T15:51:16.0960347Z     
2025-04-13T15:51:16.0960553Z         result = markitdown.convert(
2025-04-13T15:51:16.0960822Z             data_uri,
2025-04-13T15:51:16.0961052Z             url=test_vector.url,
2025-04-13T15:51:16.0961277Z         )
2025-04-13T15:51:16.0961512Z         for string in test_vector.must_include:
2025-04-13T15:51:16.0961825Z >           assert string in result.markdown
2025-04-13T15:51:16.0962454Z E           AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0963426Z E            +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f44e3020>.markdown
2025-04-13T15:51:16.0963940Z 
2025-04-13T15:51:16.0964103Z tests/test_module_vectors.py:160: AssertionError
2025-04-13T15:51:16.0964462Z =============================== warnings summary ===============================
2025-04-13T15:51:16.0965099Z ../../../../../.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170
2025-04-13T15:51:16.0966470Z   /home/runner/.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
2025-04-13T15:51:16.0967525Z     warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2025-04-13T15:51:16.0967868Z 
2025-04-13T15:51:16.0968205Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-04-13T15:51:16.0968650Z =========================== short test summary info ============================
2025-04-13T15:51:16.0969560Z FAILED tests/test_cli_vectors.py::test_output_to_stdout[test_vector6] - assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n'
2025-04-13T15:51:16.0971258Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
2025-04-13T15:51:16.0972938Z FAILED tests/test_cli_vectors.py::test_output_to_file[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0974244Z FAILED tests/test_cli_vectors.py::test_input_from_stdin_without_hints[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |\n'
2025-04-13T15:51:16.0975684Z FAILED tests/test_module_vectors.py::test_convert_local[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0976838Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f441aae0>.markdown
2025-04-13T15:51:16.0978163Z FAILED tests/test_module_vectors.py::test_convert_stream_with_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0979345Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f63ba8d0>.markdown
2025-04-13T15:51:16.0980601Z FAILED tests/test_module_vectors.py::test_convert_stream_without_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0981909Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f7bf4890>.markdown
2025-04-13T15:51:16.0983084Z FAILED tests/test_module_vectors.py::test_convert_file_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0984223Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f9ef8260>.markdown
2025-04-13T15:51:16.0985410Z FAILED tests/test_module_vectors.py::test_convert_data_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |'
2025-04-13T15:51:16.0986537Z  +  where '| ���O | �N�� | �Z�� |\n| --- | --- | --- |\n| �������Y | 30 | ���� |\n| �O�؉p�q | 25 | ��� |\n| �����~ | 35 | ���É� |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f31f44e3020>.markdown
2025-04-13T15:51:16.0987211Z ============ 8 failed, 133 passed, 31 skipped, 1 warning in 53.42s =============
2025-04-13T15:51:16.3925899Z ##[error]Process completed with exit code 1.
