Requested labels: ubuntu-latest
Job defined at: microsoft/markitdown/.github/workflows/tests.yml@refs/pull/1176/merge
Waiting for a runner to pick up this job...
Job is waiting for a hosted runner to come online.
Job is about to start running on the hosted runner: GitHub Actions 920 (hosted)
Current runner version: '2.323.0'
##[group]Operating System
Ubuntu
24.04.2
LTS
##[endgroup]
##[group]Runner Image
Image: ubuntu-24.04
Version: 20250406.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250406.1/images/ubuntu/Ubuntu2404-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250406.1
##[endgroup]
##[group]Runner Image Provisioner
2.0.422.1
##[endgroup]
##[group]GITHUB_TOKEN Permissions
read

read
##[endgroup]
None



'actions/checkout@v4'
Version: 4.2.2
ccb2698953eaebd21c7bf6268a94f9c26518a7e38e27e0b83c1fe1ad049819b1
11bd71901bbe5b1630ceea73d27597364c9af683
##[endgroup]
'actions/setup-python@v5'
Version: 5.5.0
1fac95d751afd58314aebd2ab01d4bf3b3109a441917bd2cac2a22898ec494f7
8d9ed9ac5c53483de85588cdf95a591a75ab9f55
##[endgroup]
tests
actions/checkout@v4

microsoft/markitdown



true


1



false

##[endgroup]
microsoft/markitdown

'/home/runner/work/markitdown/markitdown'

2 49 0
##[endgroup]
Temporarily overriding HOME='/home/runner/work/_temp/2f4019c8-cebf-4cc2-8026-e42d9225f8ab' before making global git config changes

[command]/usr/bin/git config --global --add safe.directory /home/runner/work/markitdown/markitdown
'/home/runner/work/markitdown/markitdown'

/home/runner/work/markitdown/markitdown










/home/runner/work/markitdown/markitdown/.git/
https://github.com/microsoft/markitdown
##[endgroup]

[command]/usr/bin/git config --local gc.auto 0
##[endgroup]

core\.sshCommand
'core\.sshCommand' 'core.sshCommand'
http\.https\:\/\/github\.com\/\.extraheader
'http\.https\:\/\/github\.com\/\.extraheader' 'http.https://github.com/.extraheader'
--local
##[endgroup]

2 --no-tags --prune --no-recurse-submodules --depth=1 origin +521d33b41a2163b2857085a9cd21f84edbd5eb4b:refs/remotes/pull/1176/merge
https://github.com/microsoft/markitdown
521d33b41a2163b2857085a9cd21f84edbd5eb4b  pull/1176/merge
##[endgroup]

##[endgroup]

[command]/usr/bin/git config --local --unset-all extensions.worktreeConfig

1176
1176
2025-04-13T16:12:14.4886010Z



2025-04-13T16:12:14.4892694Z


2025-04-13T16:12:14.4896088Z

2025-04-13T16:12:14.4897064Z

2025-04-13T16:12:14.4897956Z

2025-04-13T16:12:14.4898697Z

2025-04-13T16:12:14.4900638Z
521d33b 81f8a69a753568b71eab022731c9658e54775ffe 3fcd48cdfc651cbf508071c8d2fb7d82aeb075de
##[endgroup]
-1 --format=%H
521d33b41a2163b2857085a9cd21f84edbd5eb4b
actions/setup-python@v5

3.10
3.11
3.12


update-environment:
allow-prereleases:
freethreaded:
##[endgroup]

3 10 16
3 11 11
3 12 9
##[endgroup]
##[group]Run pipx install hatch
[36;1mpipx install hatch[0m
0

3 12 9
3 12 9
3 12 9
Python2 3 12 9
Python3 3 12 9
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib:/opt/hostedtoolcache/Python/3.11.11/x64/lib:/opt/hostedtoolcache/Python/3.10.16/x64/lib
##[endgroup]
creating virtual environment...
installing hatch...
done! ✨ 🌟 ✨
installed package hatch 1.14.1, installed using Python 3.12.3
These apps are now globally available
- hatch
##[group]Run cd packages/markitdown; hatch test
[36;1mcd packages/markitdown; hatch test[0m
0

3 12 9
3 12 9
3 12 9
Python2 3 12 9
Python3 3 12 9
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib:/opt/hostedtoolcache/Python/3.11.11/x64/lib:/opt/hostedtoolcache/Python/3.10.16/x64/lib
##[endgroup]
Creating environment: hatch-test.py3.12
Installing project in development mode
Checking dependencies
Syncing dependencies
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/runner/work/markitdown/markitdown/packages/markitdown
configfile: pyproject.toml
plugins: rerunfailures-14.0, anyio-4.9.0, xdist-3.6.1, mock-3.14.0
collected 172 items
2025-04-13T16:12:28.4520604Z
tests/test_cli_misc.py ..                                                [  1%]
tests/test_cli_vectors.py ......F...........F...........F.....ssssssssss [ 27%]
ss..                                                                     [ 30%]
tests/test_module_misc.py ......ss.ss                                    [ 36%]
tests/test_module_vectors.py ........................F..............F... [ 61%]
...........F.....sssssssssssssss.........F..............F.........       [100%]
2025-04-13T16:13:20.3129875Z
=================================== FAILURES ===================================
_____________________ test_output_to_stdout[test_vector6] ______________________
2025-04-13T16:13:20.3131502Z
shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3134850Z
@pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
def test_output_to_stdout(shared_tmp_dir, test_vector) -> None:
"""Test that the CLI outputs to stdout correctly."""
2025-04-13T16:13:20.3137159Z
result = subprocess.run(
[
"python",
"-m",
"markitdown",
os.path.join(TEST_FILES_DIR, test_vector.filename),
],
capture_output=True,
text=True,
)
2025-04-13T16:13:20.3141703Z
assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
for test_string in test_vector.must_include:
>           assert test_string in result.stdout
E           assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
2025-04-13T16:13:20.3148828Z
tests/test_cli_vectors.py:67: AssertionError
______________________ test_output_to_file[test_vector6] _______________________
2025-04-13T16:13:20.3150230Z
shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3153553Z
@pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
def test_output_to_file(shared_tmp_dir, test_vector) -> None:
"""Test that the CLI outputs to a file correctly."""
2025-04-13T16:13:20.3155685Z
output_file = os.path.join(shared_tmp_dir, test_vector.filename + ".output")
result = subprocess.run(
[
"python",
"-m",
"markitdown",
"-o",
output_file,
os.path.join(TEST_FILES_DIR, test_vector.filename),
],
capture_output=True,
text=True,
)
2025-04-13T16:13:20.3161183Z
assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
assert os.path.exists(output_file), f"Output file not created: {output_file}"
2025-04-13T16:13:20.3162838Z
with open(output_file, "r") as f:
output_data = f.read()
for test_string in test_vector.must_include:
>               assert test_string in output_data
E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3165751Z
tests/test_cli_vectors.py:96: AssertionError
______________ test_input_from_stdin_without_hints[test_vector6] _______________
2025-04-13T16:13:20.3166854Z
shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3169339Z
@pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
def test_input_from_stdin_without_hints(shared_tmp_dir, test_vector) -> None:
"""Test that the CLI readds from stdin correctly."""
2025-04-13T16:13:20.3171407Z
test_input = b""
with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
test_input = stream.read()
2025-04-13T16:13:20.3173393Z
result = subprocess.run(
[
"python",
"-m",
"markitdown",
os.path.join(TEST_FILES_DIR, test_vector.filename),
],
input=test_input,
capture_output=True,
text=False,
)
2025-04-13T16:13:20.3177170Z
stdout = result.stdout.decode(locale.getpreferredencoding())
assert (
result.returncode == 0
), f"CLI exited with error: {result.stderr.decode('utf-8')}"
for test_string in test_vector.must_include:
>           assert test_string in stdout
E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
2025-04-13T16:13:20.3181282Z
tests/test_cli_vectors.py:129: AssertionError
_______________________ test_convert_local[test_vector9] _______________________
2025-04-13T16:13:20.3182365Z
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3184369Z
@pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
def test_convert_local(test_vector):
"""Test the conversion of a local file."""
markitdown = MarkItDown()
2025-04-13T16:13:20.3186310Z
result = markitdown.convert(
os.path.join(TEST_FILES_DIR, test_vector.filename), url=test_vector.url
)
for string in test_vector.must_include:
>           assert string in result.markdown
E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55fa302a80>.markdown
2025-04-13T16:13:20.3191480Z
tests/test_module_vectors.py:69: AssertionError
_________________ test_convert_stream_with_hints[test_vector9] _________________
2025-04-13T16:13:20.3192629Z
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3194458Z
@pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
def test_convert_stream_with_hints(test_vector):
"""Test the conversion of a stream with full stream info."""
markitdown = MarkItDown()
2025-04-13T16:13:20.3196641Z
stream_info = StreamInfo(
extension=os.path.splitext(test_vector.filename)[1],
mimetype=test_vector.mimetype,
charset=test_vector.charset,
)
2025-04-13T16:13:20.3199042Z
with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
result = markitdown.convert(
stream, stream_info=stream_info, url=test_vector.url
)
for string in test_vector.must_include:
>               assert string in result.markdown
E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
E                +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9dc9910>.markdown
2025-04-13T16:13:20.3204929Z
tests/test_module_vectors.py:90: AssertionError
_______________ test_convert_stream_without_hints[test_vector9] ________________
2025-04-13T16:13:20.3206053Z
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3207821Z
@pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
def test_convert_stream_without_hints(test_vector):
"""Test the conversion of a stream with no stream info."""
markitdown = MarkItDown()
2025-04-13T16:13:20.3210193Z
with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
result = markitdown.convert(stream, url=test_vector.url)
for string in test_vector.must_include:
>               assert string in result.markdown
E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
E                +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9da0c50>.markdown
2025-04-13T16:13:20.3215439Z
tests/test_module_vectors.py:103: AssertionError
_____________________ test_convert_file_uri[test_vector9] ______________________
2025-04-13T16:13:20.3216562Z
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3218418Z
@pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
def test_convert_file_uri(test_vector):
"""Test the conversion of a file:// URI."""
markitdown = MarkItDown()
2025-04-13T16:13:20.3220389Z
result = markitdown.convert(
Path(os.path.join(TEST_FILES_DIR, test_vector.filename)).as_uri(),
url=test_vector.url,
)
for string in test_vector.must_include:
>           assert string in result.markdown
E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f831fad0>.markdown
2025-04-13T16:13:20.3225932Z
tests/test_module_vectors.py:139: AssertionError
_____________________ test_convert_data_uri[test_vector9] ______________________
2025-04-13T16:13:20.3227021Z
test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3228846Z
@pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
def test_convert_data_uri(test_vector):
"""Test the conversion of a data URI."""
markitdown = MarkItDown()
2025-04-13T16:13:20.3230735Z
data = ""
with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
data = base64.b64encode(stream.read()).decode("utf-8")
mimetype = test_vector.mimetype
data_uri = f"data:{mimetype};base64,{data}"
2025-04-13T16:13:20.3233586Z
result = markitdown.convert(
data_uri,
url=test_vector.url,
)
for string in test_vector.must_include:
>           assert string in result.markdown
E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f83f79b0>.markdown
2025-04-13T16:13:20.3238568Z
tests/test_module_vectors.py:160: AssertionError
=============================== warnings summary ===============================
../../../../../.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170
/home/runner/.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2025-04-13T16:13:20.3244307Z
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_cli_vectors.py::test_output_to_stdout[test_vector6] - assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
FAILED tests/test_cli_vectors.py::test_output_to_file[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
FAILED tests/test_cli_vectors.py::test_input_from_stdin_without_hints[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
FAILED tests/test_module_vectors.py::test_convert_local[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55fa302a80>.markdown
FAILED tests/test_module_vectors.py::test_convert_stream_with_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9dc9910>.markdown
FAILED tests/test_module_vectors.py::test_convert_stream_without_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9da0c50>.markdown
FAILED tests/test_module_vectors.py::test_convert_file_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f831fad0>.markdown
FAILED tests/test_module_vectors.py::test_convert_data_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
+  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f83f79b0>.markdown
============ 8 failed, 133 passed, 31 skipped, 1 warning in 55.66s =============
##[error]Process completed with exit code 1.


2 49 0
Temporarily overriding HOME='/home/runner/work/_temp/27701047-55e4-4eb6-a51f-fe28f5021f6e' before making global git config changes

[command]/usr/bin/git config --global --add safe.directory /home/runner/work/markitdown/markitdown
core\.sshCommand
'core\.sshCommand' 'core.sshCommand'
http\.https\:\/\/github\.com\/\.extraheader


'http\.https\:\/\/github\.com\/\.extraheader' 'http.https://github.com/.extraheader'

