2025-03-11T06:53:05.3189073Z ##[group]Run git push origin main  # Push changes to the main branch
2025-03-11T06:53:05.3189534Z [36;1mgit push origin main  # Push changes to the main branch[0m
2025-03-11T06:53:05.3235670Z shell: /usr/bin/bash -e {0}
2025-03-11T06:53:05.3235905Z env:
2025-03-11T06:53:05.3236089Z   DETERMINATE_NIX_KVM: 1
2025-03-11T06:53:05.3236304Z   tag: v1.4.155
2025-03-11T06:53:05.3236500Z   new_version: 1.4.156
2025-03-11T06:53:05.3236699Z   new_tag: v1.4.156
2025-03-11T06:53:05.3237096Z   GITHUB_TOKEN: ***
2025-03-11T06:53:05.3237295Z ##[endgroup]
2025-03-11T06:53:05.4482539Z To https://github.com/danielmiessler/fabric
2025-03-11T06:53:05.4483111Z  ! [rejected]        main -> main (fetch first)
2025-03-11T06:53:05.4484026Z error: failed to push some refs to 'https://github.com/danielmiessler/fabric'
2025-03-11T06:53:05.4492941Z hint: Updates were rejected because the remote contains work that you do not
2025-03-11T06:53:05.4494218Z hint: have locally. This is usually caused by another repository pushing to
2025-03-11T06:53:05.4494994Z hint: the same ref. If you want to integrate the remote changes, use
2025-03-11T06:53:05.4495515Z hint: 'git pull' before pushing again.
2025-03-11T06:53:05.4495871Z hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2025-03-11T06:53:05.4508214Z ##[error]Process completed with exit code 1.
